#!/usr/bin/env bash -x -e -u -o pipefail

###############################################################################
# Variables.
###############################################################################

RANDOM_SOURCE=''
SSD=''
RAW_DEVICE_NAME=''
LVM_DEVICE_NAME=''
LUKS_DEVICE_NAME=''
MNT_POINT=''
PASSPHRASE=''
CACHE_DIR=''
LOCALE=''
HOSTNAME=''
TIMEZONE=''
PASSWORD=''
CONFIG_DIR=''

###############################################################################
# Configuration functions.
###############################################################################

usage() {
   echo <<EOT
Usage: $SCRIPT_FILE [OPTIONS]
Options:
   -h                Display this help message and exit.
   -r                Randomize disk contents using /dev/random.
   -u                Randomize disk contents using /dev/urandom.
   -s                Is the raw device a solid state drive?
   -d <device>       Raw device (disk).
   -l <device>       LVM device name.
   -k <device>       Luks device name.
   -m <mount point>  Installation mount point.
   -p <passphrase>   Root volume passphrase.
   -c <cache dir>    Package cache directory.
   -L <locale>       System locale.
   -n <hostname>     System hostname.
   -t <timezone>     System timezone.
   -w <password>     Root user password.
   -f <config dir>   Directory containing configuration files.
EOT
}

parse_cmd_line() {
   while getopts "hrusdlkmpwcLntf:" opt; do
      case "$opt" in
         h)
            _usage
            exit 0
            ;;
         r)
            [ "$random" ] && _error "Only a single 'random' or 'urandom' flag can be specified."
            RANDOM_SOURCE='random'
            ;;
         u)
            [ "$random" ] && _error "Only a single 'random' or 'urandom' flag can be specified."
            RANDOM_SOURCE='urandom'
            ;;
         s)
            [ "$SSD" ] && _error "SSD flag can only be specified once."
            SSD='true'
            ;;
         d)
            [ "$RAW_DEVICE_NAME" ] && _error "Only one raw device can be specified."
            RAW_DEVICE_NAME="$OPTARG"
            ;;
         l)
            [ "$LVM_DEVICE_NAME" ] && _error "Only one LVM device can be specified."
            LVM_DEVICE_NAME="$OPTARG"
            ;;
         k)
            [ "$LUKS_DEVICE_NAME" ] && _error "Only one luks device can be specified."
            LUKS_DEVICE_NAME="$OPTARG"
            ;;
         m)
            [ "$MNT_POINT" ] && _error "Only one mount point can be specified."
            MNT_POINT="$OPTARG"
            ;;
         p)
            [ "$PASSPHRASE" ] && _error "Only one passphrase can be specified."
            PASSPHRASE="$OPTARG"
            ;;
         c)
            [ "$CACHE_DIR" ] && _error "Only one cache directory can be specified."
            CACHE_DIR="$OPTARG"
            ;;
         L)
            [ "$LOCALE" ] && _error "Only one locale can be specified."
            LOCALE="$OPTARG"
            ;;
         n)
            [ "$HOSTNAME" ] && _error "Only one hostname can be specified."
            HOSTNAME="$OPTARG"
            ;;
         t)
            [ "$TIMEZONE" ] && _error "Only one timezone can be specified."
            TIMEZONE="$OPTARG"
            ;;
         w)
            [ "$PASSWORD" ] && _error "Only one password can be specified."
            PASSWORD="$OPTARG"
            ;;
         f)
            [ "$CACHE_DIR" ] && _error "Only one cache directory can be specified."
            CACHE_DIR="$OPTARG"
            ;;
         \?)
            _usage
            exit 1
            ;;
      esac
   done
}

validate_cmd_line() {
   [ "$RAW_DEVICE_NAME" ] || _error "A raw device can be specified."
   [ "$LVM_DEVICE_NAME" ] || _error "A LVM device can be specified."
   [ "$LUKS_DEVICE_NAME" ] || _error "A luks device can be specified."
   [ "$MNT_POINT" ] || _error "A mount point can be specified."
   [ "$PASSPHRASE" ] || _error "A passphrase can be specified."
   [ "$CACHE_DIR" ] || _error "A cache directory can be specified."
   [ "$LOCALE" ] || _error "A locale can be specified."
   [ "$HOSTNAME" ] || _error "A hostname can be specified."
   [ "$TIMEZONE" ] || _error "A timezone can be specified."
   [ "$PASSWORD" ] || _error "A password can be specified."
   [ "$CACHE_DIR" ] || _error "A cache directory can be specified."
}


###############################################################################
# Instructions.
###############################################################################

bash -x -e -o pipefail ./scripts/prepare
bash -x -e -o pipefail ./scripts/install
bash -x -e -o pipefail ./scripts/configure
bash -x -e -o pipefail ./scripts/cleanup

