#!/bin/bash

timeout=30

# Check system uptime
[ -e /var/run/last-resume ] || touch /var/run/last-resume
if find /var/run/ -maxdepth 1 -type f -name last-resume -cmin -$timeout | grep -q .; then
   exit 1
fi

# Check for active tmux sessions
if pgrep -l '^tmux$'; then
   exit 1
fi

# Check for active user
if [ -d /var/run/system-login/active ]; then
   for file in $(find /var/run/system-login/active -type f -printf "%f\n"); do
      if pgrep -P "$file" > /dev/null; then
         exit 1
      else
         rm "/var/run/system-login/active/$file"
      fi
   done
fi

# Check for logouts that where at least $timeout minutes ago
if [ -d /var/run/system-login/inactive ]; then
   for file in $(find /var/run/system-login/inactive -cmin -$timeout -type f -printf "%f\n"); do
      exit 1
   done
fi

exit 0
