#!/usr/bin/env bash
set -ex -o pipefail -o nounset

# Raw Partition

parted --script --align optimal -- /dev/sda mklabel gpt

parted --script --align optimal -- /dev/sda mkpart primary 2 4
parted --script --align optimal -- /dev/sda name 1 bios_grub
parted --script --align optimal -- /dev/sda set 1 bios_grub on

parted --script --align optimal -- /dev/sda mkpart primary 4 204
parted --script --align optimal -- /dev/sda name 2 boot
parted --script --align optimal -- /dev/sda set 2 boot on

parted --script --align optimal -- /dev/sda mkpart primary 204 -1
parted --script --align optimal -- /dev/sda name 3 lvm
parted --script --align optimal -- /dev/sda set 3 lvm on

# LVM Partition

pvcreate -ff /dev/sda3
vgcreate LvmDvc /dev/sda3
lvcreate --name root --size 2G LvmDvc
lvcreate --name home --size 2G LvmDvc
lvcreate --name var --size 1G LvmDvc
lvcreate --name usr --size 1G LvmDvc
lvcreate --name swap --size 4G LvmDvc

# Format

mkfs.ext4 -q /dev/sda2
mkfs.ext4 -q /dev/LvmDvc/root
mkfs.ext4 -q /dev/LvmDvc/home
mkfs.ext4 -q /dev/LvmDvc/var
mkfs.ext4 -q /dev/LvmDvc/usr
mkswap /dev/LvmDvc/swap

# Mount

mkdir -p /mnt/archbox
mount /dev/LvmDvc/root /mnt/archbox

mkdir -p /mnt/archbox/boot
mount /dev/sda2 /mnt/archbox/boot

mkdir -p /mnt/archbox/home
mount /dev/LvmDvc/home /mnt/archbox/home

mkdir -p /mnt/archbox/var
mount /dev/LvmDvc/var /mnt/archbox/var

mkdir -p /mnt/archbox/usr
mount /dev/LvmDvc/usr /mnt/archbox/usr

swapon /dev/LvmDvc/swap
