#!/usr/bin/env bash
set -ex -o pipefail -o nounset

umount -R /mnt/archbox
swapoff /dev/mapper/LuksDvc-swap

cryptsetup luksClose /dev/mapper/LuksDvc-root
cryptsetup luksClose /dev/mapper/LuksDvc-home
cryptsetup luksClose /dev/mapper/LuksDvc-usr
cryptsetup luksClose /dev/mapper/LuksDvc-var
cryptsetup luksClose /dev/mapper/LuksDvc-swap

vgchange --activate n LvmDvc
