#!/usr/bin/env bash
set -ex -o pipefail -o nounset

umount -R /mnt/archbox
swapoff /dev/LvmDvc/swap

cryptsetup luksClose /dev/mapper/root
cryptsetup luksClose /dev/mapper/home
cryptsetup luksClose /dev/mapper/usr
cryptsetup luksClose /dev/mapper/var
cryptsetup luksClose /dev/mapper/swap

vgchange --activate n LvmDvc
