#!/usr/bin/env bash
set -ex -o pipefail -o nounset

# Raw Partitioning

parted --script --align optimal -- /dev/sda mklabel gpt

parted --script --align optimal -- /dev/sda mkpart primary 2 4
parted --script --align optimal -- /dev/sda name 1 bios_grub
parted --script --align optimal -- /dev/sda set 1 bios_grub on

parted --script --align optimal -- /dev/sda mkpart primary 4 204
parted --script --align optimal -- /dev/sda name 2 boot
parted --script --align optimal -- /dev/sda set 2 boot on

parted --script --align optimal -- /dev/sda mkpart primary 204 -1
parted --script --align optimal -- /dev/sda name 3 lvm
parted --script --align optimal -- /dev/sda set 3 lvm on

# LVM Partitioning

pvcreate -ff --yes /dev/sda3
vgcreate LvmDvc /dev/sda3
lvcreate --zero y --wipesignatures y --name root --size 3G LvmDvc
lvcreate --zero y --wipesignatures y --name home --size 2G LvmDvc
lvcreate --zero y --wipesignatures y --name var --size 1G LvmDvc
lvcreate --zero y --wipesignatures y --name swap --size 6G LvmDvc

# Root Partition

echo asdfasdf | cryptsetup -q luksFormat /dev/mapper/LvmDvc-root
echo asdfasdf | cryptsetup -q luksOpen /dev/mapper/LvmDvc-root root
mkfs.ext4 -q /dev/mapper/root

mkdir -p /mnt/archbox
mount /dev/mapper/root /mnt/archbox

# Boot Partition

mkfs.ext4 -q /dev/sda2

# Encrypted Partitions

mkdir -p /mnt/archbox/etc/cryptkeys
chmod 400 /mnt/archbox/etc/cryptkeys

dd if=/dev/random of=/mnt/archbox/etc/cryptkeys/home bs=2048 count=1 iflag=fullblock
chmod 400 /mnt/archbox/etc/cryptkeys/home
cryptsetup -q --key-file /mnt/archbox/etc/cryptkeys/home luksFormat /dev/mapper/LvmDvc-home
cryptsetup -q --key-file /mnt/archbox/etc/cryptkeys/home luksOpen /dev/mapper/LvmDvc-home home
mkfs.ext4 -q /dev/mapper/home

dd if=/dev/random of=/mnt/archbox/etc/cryptkeys/var bs=2048 count=1 iflag=fullblock
chmod 400 /mnt/archbox/etc/cryptkeys/var
cryptsetup -q --key-file /mnt/archbox/etc/cryptkeys/var luksFormat /dev/mapper/LvmDvc-var
cryptsetup -q --key-file /mnt/archbox/etc/cryptkeys/var luksOpen /dev/mapper/LvmDvc-var var
mkfs.ext4 -q /dev/mapper/var

# Mount

mount_options='defaults,noatime,discard'

general_tmpfs_mount_options='rw,nodev,noatime,async,auto,nouser,nr_inodes=4k'
strict_tmpfs_mount_options='noexec,nosuid,mode=0777'
base_tmpfs_mount_options="$general_tmpfs_mount_options,$strict_tmpfs_mount_options"
normal_tmpfs_mount_options="$base_tmpfs_mount_options,size=1g"
large_tmpfs_mount_options="$base_tmpfs_mount_options,size=2g"

mkdir -p /mnt/archbox/boot
mount -t ext4 -o "$mount_options" /dev/sda2 /mnt/archbox/boot

mkdir -p /mnt/archbox/home
mount -t ext4 -o "$mount_options" /dev/mapper/home /mnt/archbox/home

mkdir -p /mnt/archbox/var
mount -t ext4 -o "$mount_options" /dev/mapper/var /mnt/archbox/var

mount -t tmpfs -o "$large_tmpfs_mount_options" tmpfs /tmp
mount -t tmpfs -o "$normal_tmpfs_mount_options" tmpfs /var/cache
mount -t tmpfs -o "$normal_tmpfs_mount_options" tmpfs /usr/src
mount -t tmpfs -o "$normal_tmpfs_mount_options" tmpfs /usr/local/src
