#!/usr/bin/env bash
set -ex -o pipefail -o nounset

# Packages

mkdir -p ./cache-dir
rm -f /mnt/archbox/var/lib/pacman/db.lck
pacstrap /mnt/archbox --cachedir ./cache-dir base grub

# Root password

echo "root:asdfasdf" | chpasswd --root /mnt/archbox

# FSTab

boot_uuid=$(blkid -o value -s PARTUUID /dev/sda2)

rm -f /mnt/archbox/etc/fstab
touch /mnt/archbox/etc/fstab

echo -e "# <file system>\t<dir>\t<type>\t<options>\t<dump>\t<pass>" >> /mnt/archbox/etc/fstab
echo -e "/dev/mapper/root\t/\tetx4\tdefaults,noatime,discard\t0\t1" >> /mnt/archbox/etc/fstab
echo -e "UUID=$boot_uuid\t/boot\tetx4\tdefaults,noatime,discard\t0\t2" >> /mnt/archbox/etc/fstab
echo -e "/dev/mapper/home\t/home\tetx4\tdefaults,noatime,discard,x.systemd-automount\t0\t2" >> /mnt/archbox/etc/fstab
echo -e "/dev/mapper/var\t/var\tetx4\tdefaults,noatime,discard\t0\t2" >> /mnt/archbox/etc/fstab
echo -e "/dev/mapper/swap\tnone\tswap\tdefaults,discard\t0\t0" >> /mnt/archbox/etc/fstab

# CryptTab

rm -f /mnt/archbox/etc/crypttab
touch /mnt/archbox/etc/crypttab

echo -e "home\t/dev/mapper/LvmDvc-home\t/etc/cryptkeys/home" >> /mnt/archbox/etc/crypttab
echo -e "var\t/dev/mapper/LvmDvc-var\t/etc/cryptkeys/var" >> /mnt/archbox/etc/crypttab
echo -e "swap\t/dev/mapper/LvmDvc-swap\t/etc/cryptkeys/swap" >> /mnt/archbox/etc/crypttab

# Ramdisk

file=/mnt/archbox/etc/mkinitcpio.conf

search="^\s*MODULES=.*$"
replace="MODULES=\\\"virtio virtio_blk virtio_pci virtio_net\\\""
grep -q "$search" "$file" && sed -i "s#$search#$replace#" "$file" || echo "$replace" >> "$file"

search="^\s*HOOKS=.*$"
replace="HOOKS=\\\"base udev autodetect modconf block keymap encrypt lvm2 filesystems keyboard shutdown fsck\\\""
grep -q "$search" "$file" && sed -i "s#$search#$replace#" "$file" || echo "$replace" >> "$file"

arch-chroot /mnt/archbox mkinitcpio -p linux

# Bootloader

arch-chroot /mnt/archbox grub-install --target=i386-pc --recheck /dev/sda

file=/mnt/archbox/etc/default/grub

search="^\s*GRUB_CMDLINE_LINUX=.*$"
replace="GRUB_CMDLINE_LINUX=\\\"init=/usr/lib/systemd/systemd cryptdevice=/dev/mapper/LvmDvc-root:root root=/dev/mapper/root\\\""
grep -q "$search" "$file" && sed -i "s#$search#$replace#" "$file" || echo "$replace" >> "$file"

search="^\s*GRUB_DISABLE_LINUX_UUID=.*$"
replace="GRUB_DISABLE_LINUX_UUID=true"
grep -q "$search" "$file" && sed -i "s#$search#$replace#" "$file" || echo "$replace" >> "$file"

arch-chroot /mnt/archbox grub-mkconfig -o /boot/grub/grub.cfg
