#!/usr/bin/env bash
set -ex -o pipefail -o nounset

###############################################################################
# Command wrappers.
###############################################################################

_parted() {
   parted --script --align optimal -- "$@"
}

_mkpart() {
   local device="$1"
   local part="$2"
   local begin="$3"
   local end="$4"
   local name="$5"
   local flag="$6"

   [ "$device" ] && [ "$part" ] && [ "$begin" ] && [ "$end" ]

   _parted "$device" mkpart primary "$begin" "$end"
   [ "$name" ] && (_parted "$device" name "$part" "$name") || true
   [ "$flag" ] && (_parted "$device" set "$part" "$flag" on) || true
}

_lvcreate() {
   local name="$1"
   local size="$2"

   [ "$name" ] && [ "$size" ]

   lvcreate --zero y --wipesignatures y --name "$name" --size "$size" "$LV_GROUP"
}

_format() {
   local fs_type="$1"
   local device="$2"

   [ "$fs_type" ] && [ "$device" ]

   "mkfs.$fs_type" -q "$device"
}

_mount() {
   local fs_type="$1"
   local device="$2"
   local path="$3"
   local options="$4"

   [ "$fs_type" ] && [ "$device" ] && [ "$path" ] && [ "$options" ]

   mkdir -p "$path"
   mount -t "$fs_type" -o "$options" "$device" "$path"
}

format_and_mount() {
   local fs_type="$1"
   local device="$2"
   local path="$3"

   [ "$fs_type" ] && [ "$device" ] && [ "$path" ]

   local options="$(mount_options $path)"

   [ "$options" ]

   _format "$fs_type" "$device"
   _mount "$fs_type" "$device" "$path" "$options"
}

make_key() {
   local label="$1"

   [ "$label" ]

   local keyfile="$(mount_point root)$(crypt_key_file $label)"

   dd if=/dev/random of="$keyfile" bs=2048 count=1 iflag=fullblock >/dev/null 2>&1
   chmod 000 "$keyfile"

   echo "$keyfile"
}

encrypt_key() {
   local label="$1"
   local keyfile="$2"

   [ "$label" ] && [ "$keyfile" ]

   local device="$(logical_volume $label)"
   local cryptsetup="cryptsetup -q --key-file $keyfile"

   $cryptsetup luksFormat "$device"
   $cryptsetup luksOpen "$device" "$label"
}

encrypt_phrase() {
   local label="$1"
   local passphrase="$2"

   [ "$label" ] && [ "$passphrase" ]

   local device="$(logical_volume $label)"
   local cryptsetup='cryptsetup -q'

   echo "$passphrase" | $cryptsetup luksFormat "$device"
   echo "$passphrase" | $cryptsetup luksOpen "$device" "$label"
}

###############################################################################
# Disk preparation.
###############################################################################

make_raw_partitions() {
   _parted "$RAW_DEVICE_PATH" mklabel gpt

   local index=1
   local begin=2
   local end=

   for label in $(echo $RAW_PARTITIONS); do
      local name=
      local size=
      local flag=
      local mount=

      local partition="RAW_PARTITION_$label"
      for var in $(echo ${!partition}); do
         eval $var
      done

      [ "_$size" = '_-1' ] && end=-1 || end="$(expr $begin + $size)"

      _mkpart "$RAW_DEVICE_PATH" "$index" "$begin" "$end" "$name" "$flag"

      index="$(expr $index + 1)"
      begin="$end"

      unset name
      unset size
      unset flag
      unset mount
   done
}

make_logical_volumes() {
   pvcreate -ff --yes "$(lvm_partition)"
   vgcreate "$LV_GROUP" "$(lvm_partition)"

   for label in $(echo $LOGICAL_VOLUMES); do
      local name=
      local size=
      local mount=

      local partition="LOGICAL_VOLUME_$label"
      for var in $(echo ${!partition}); do
         eval $var
      done

      _lvcreate "$name" "$size"

      unset name
      unset size
      unset mount
   done
}

make_luks_containers() {
   mkdir -p "$(mount_point root)$(crypt_key_dir)"
   chmod 000 "$(mount_point root)$(crypt_key_dir)"

   for label in $(echo $LUKS_CONTAINERS); do
      encrypt_key "$label" "$(make_key $label)"
      format_and_mount ext4 "$(luks_container $label)" "$(mount_point $label)"
   done
}

mount_tmpfs_directories() {
   for label in $(echo $TMPFS_DIRECTORIES); do
      local size=
      local mount=

      local partition="TMPFS_DIRECTORY_$label"
      for var in $(echo ${!partition}); do
         eval $var
      done

      local options="$(mount_tmpfs_options $mount)"

      _mount tmpfs tmpfs "$mount" "$options"
   done
}

###############################################################################
# Instructions.
###############################################################################

make_raw_partitions
make_logical_volumes

# Root
encrypt_phrase root "$PASSPHRASE"
format_and_mount ext4 "$(luks_container root)" "$(mount_point root)"

# Boot
format_and_mount ext4 "$(boot_partition)" "$(mount_point boot)"

# Encrypted
make_luks_containers

# TMPFS
mount_tmpfs_directories
